environment: 1
log_level: 6
address: :3000
cors:
  - http://localhost:3000
admin_secret: 7GRPpVk04We76CWR
projector_secret: wdvXuDOytfx84J8d
student_secret: XrO3ole8bS83OQ3p
MySql: user:pass@tcp(127.0.0.1:3306)/dbname?charset=utf8mb4&parseTime=True&loc=Local